version: '3.4'
services:

  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./model:/app/model
    - ./data:/app/data
    - ./envirocar_channel:/app/envirocar_channel
    - ./enums:/app/enums
    - ./utils:/app/utils
    command: bash -c "rm -rf models/* && rasa train && rasa run --credentials credentials.yml --endpoints local-endpoints.yml --enable-api -p 5006 --cors \"*\" --debug"
    ports:
    - '5007:5006'
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./model:/app/model
    - ./envirocar_channel:/app/envirocar_channel
    - ./enums:/app/enums
    - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
