name: Secret Test

on: [workflow_dispatch]

jobs:
  secret-testing:
    name: Test Github Toekn Secret
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - shell: bash
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "$TOKEN"
